// src/features/ongeki/OngekiRecentItem.tsx
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { BModal } from '@/components/shared/BModal';
import { assetsHost, enableImages } from '@/lib/utils';
import { padDigits } from '@/lib/format';
import { toBattleSprite, toTechSprite, toLevelDecimal } from './pipes';
import { OngekiCardLevel } from './OngekiCardLevel';
import { OngekiSongScoreRanking } from './OngekiSongScoreRanking';
import { Difficulty, type OngekiMusic, type PlayerPlaylog } from './models';
import './recent-item.css';
import './ongeki-common.css';

const DIFF_NAMES: Record<number, string> = {
  0: 'Basic',
  1: 'Advanced',
  2: 'Expert',
  3: 'Master',
  10: 'Lunatic',
};

const ATTR_NAMES: Record<number, string> = { 1: 'Fire', 2: 'Aqua', 3: 'Leaf', 4: 'Max' };

/** 等价旧版 ongeki-recent-item.component（单条游玩记录） */
export function OngekiRecentItem({ playLog }: { playLog: PlayerPlaylog }) {
  const { t } = useTranslation();
  const [detailsOpen, setDetailsOpen] = useState(false);
  const [rankingMusic, setRankingMusic] = useState<OngekiMusic | null>(null);

  const level = playLog.level;
  const levelData =
    level === 0
      ? playLog.songInfo?.level0
      : level === 1
        ? playLog.songInfo?.level1
        : level === 2
          ? playLog.songInfo?.level2
          : level === 3
            ? playLog.songInfo?.level3
            : playLog.songInfo?.level4;

  const diffClass: Record<string, string> = {
    Basic: 'difficulty-basic',
    Advanced: 'difficulty-advanced',
    Expert: 'difficulty-expert',
    Master: 'difficulty-master',
    Lunatic: 'difficulty-lunatic',
  };

  const platinumStars = playLog.platinumScoreStar ?? 0;

  return (
    <div className="card ongeki-recent-item">
      <div className="recent-song-info card-header hstack gap-2">
        <div className="jacket-container ratio ratio-1x1">
          {enableImages && (
            <img
              className="jacket"
              src={assetsHost + `assets/ongeki/jacket/UI_Jacket_${padDigits(playLog.musicId, 4)}.webp`}
              alt=""
            />
          )}
        </div>
        <div className="overflow-hidden">
          <div className="song-info-title text-truncate fw-bold">
            <span>{playLog.songInfo != null ? playLog.songInfo.name : `MusicID:${playLog.musicId}`}</span>
          </div>
          <div className="song-info-artist text-truncate">
            <span>
              {playLog.songInfo != null
                ? playLog.songInfo.artistName
                : t('Ongeki.RecentPage.UnknownArtist')}
            </span>
          </div>
          <div>
            <span className={'difficulty ' + diffClass[DIFF_NAMES[level]] + ' badge rounded-pill'}>
              {DIFF_NAMES[level]} {levelData ? toLevelDecimal(levelData) ?? 'None' : 'None'}
            </span>
          </div>
        </div>
      </div>
      <div className="play-result card-body">
        <div className="row align-items-center">
          <div className="score-area col-12 col-md-6">
            <div className="row text-nowrap">
              <div className="col-6 col-sm-3 col-md-6 col-lg-3 text-end">
                <div className="item-header battle-item-header">
                  <span>BATTLE SCORE</span>
                </div>
                <div className={'score' + (playLog.isBattleNewRecord ? ' new-record' : '')}>
                  <span className="score-font-large">{Math.floor(playLog.battleScore / 10000)}</span>
                  <span className="score-font-small">{padDigits(playLog.battleScore % 10000, 4)}</span>
                </div>
                <div className="item-header battle-item-header">
                  <span>OVER DAMAGE</span>
                </div>
                <div className={'score' + (playLog.isOverDamageNewRecord ? ' new-record' : '')}>
                  <span className="score-font-large">{Math.floor(playLog.overDamage / 100)}</span>
                  <span className="score-font-small">.{padDigits(playLog.overDamage % 100, 2)}%</span>
                </div>
              </div>
              <div className="col-6 col-sm-3 col-md-6 col-lg-3 align-items-center d-flex">
                {enableImages && (
                  <img
                    className="score-stamp"
                    src={assetsHost + `assets/ongeki/gameUi/${toBattleSprite(playLog.battleScoreRank)}`}
                    alt=""
                  />
                )}
              </div>
              <div className="col-6 col-sm-3 col-md-6 col-lg-3 text-end">
                <div className="item-header technical-item-header">
                  <span>TECHNICAL SCORE</span>
                </div>
                <div className={'score' + (playLog.isTechNewRecord ? ' new-record' : '')}>
                  <span className="score-font-large">{Math.floor(playLog.techScore / 10000)}</span>
                  <span className="score-font-small">{padDigits(playLog.techScore % 10000, 4)}</span>
                </div>
                <div className="item-header technical-item-header">
                  <span>PLATINUM</span>
                </div>
                <div className="score">
                  {enableImages && (
                    <div className="platinum-star-container">
                      {Array.from({ length: platinumStars }).map((_, i) => (
                        <img key={i} className="platinum-star" src={assetsHost + 'assets/ongeki/gameUi/UI_Card_star_00.webp'} alt="" />
                      ))}
                      {Array.from({ length: 5 - platinumStars }).map((_, i) => (
                        <img key={'e' + i} className="platinum-star" src={assetsHost + 'assets/ongeki/gameUi/UI_Card_star_01.webp'} alt="" />
                      ))}
                    </div>
                  )}
                  <div className="score-font-large platinum-score">{playLog.platinumScore}</div>
                </div>
              </div>
              <div className="col-6 col-sm-3 col-md-6 col-lg-3 align-items-center d-flex" style={{ maxWidth: 150 }}>
                {enableImages && (
                  <img
                    className="score-stamp"
                    src={assetsHost + `assets/ongeki/gameUi/${toTechSprite(playLog.techScoreRank)}`}
                    alt=""
                  />
                )}
              </div>
            </div>
            <div className="row row-cols-2 align-items-center">
              <div className="col-6 col-sm-auto col-md-6 col-xl-auto text-end">
                {enableImages && (
                  <img
                    className="score-honor"
                    alt=""
                    src={
                      assetsHost +
                      `assets/ongeki/gameUi/UI_RES_Score_FB_${playLog.isFullBell ? 'Badge' : 'Base'}.webp`
                    }
                  />
                )}
              </div>
              <div className="col-6 col-sm-auto col-md-6 col-xl-auto text-start">
                {enableImages && (
                  <img
                    className="score-honor"
                    alt=""
                    src={
                      assetsHost +
                      `assets/ongeki/gameUi/UI_RES_Score_${playLog.isAllBreak ? 'AB' : 'FC'}_${
                        playLog.isFullCombo ? 'Badge' : 'Base'
                      }.webp`
                    }
                  />
                )}
              </div>
            </div>
          </div>
          <div className="col-12 col-md-6">
            <div className="battle-area row">
              <div className="col-6">
                <div className="recent-chara-container">
                  <div className="chara-center position-relative">
                    <img
                      className="chara-center-img position-absolute"
                      src={
                        assetsHost +
                        `assets/ongeki/card-icon/UI_Card_Icon_${padDigits(playLog.cardInfo2?.id ?? 0, 6)}.webp`
                      }
                      alt=""
                    />
                    <OngekiCardLevel
                      className="chara-center-level position-absolute"
                      level={playLog.cardLevel2}
                      attribute={playLog.cardInfo2?.attribute ?? 'Fire'}
                    />
                  </div>
                  <div className="chara-side position-relative">
                    <img
                      className="chara-side-img position-absolute"
                      src={
                        assetsHost +
                        `assets/ongeki/card-icon/UI_Card_Icon_${padDigits(playLog.cardInfo1?.id ?? 0, 6)}.webp`
                      }
                      alt=""
                    />
                    <OngekiCardLevel
                      className="chara-side-level position-absolute"
                      level={playLog.cardLevel1}
                      attribute={playLog.cardInfo1?.attribute ?? 'Fire'}
                    />
                  </div>
                  <div className="chara-side position-relative">
                    <img
                      className="chara-side-img position-absolute"
                      src={
                        assetsHost +
                        `assets/ongeki/card-icon/UI_Card_Icon_${padDigits(playLog.cardInfo3?.id ?? 0, 6)}.webp`
                      }
                      alt=""
                    />
                    <OngekiCardLevel
                      className="chara-side-level position-absolute"
                      level={playLog.cardLevel3}
                      attribute={playLog.cardInfo3?.attribute ?? 'Fire'}
                    />
                  </div>
                </div>
              </div>
              <div className="col-6">
                <div className="boss position-relative">
                  <img
                    className="boss-img"
                    alt=""
                    src={
                      assetsHost +
                      `assets/ongeki/card-chara/UI_Card_Chara_${padDigits(playLog.songInfo?.bossCardId ?? 0, 6)}.webp`
                    }
                  />
                  <OngekiCardLevel
                    className="boss-level position-absolute"
                    level={playLog.bossLevel}
                    attribute={ATTR_NAMES[playLog.bossAttribute] ?? 'Fire'}
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="card-footer fw-bold">
        <div className="float-start">
          <a className="text-primary cursor-pointer" onClick={() => setDetailsOpen(true)}>
            {t('Ongeki.RecentPage.Details')}
          </a>
        </div>
        <div className="float-start ms-3">
          <a
            className="text-primary cursor-pointer"
            onClick={() => playLog.songInfo && setRankingMusic(playLog.songInfo)}
          >
            {t('Ongeki.RecentPage.Ranking')}
          </a>
        </div>
        <div className="float-end">
          <span>{new Date(playLog.userPlayDate).toLocaleString()}</span>
        </div>
      </div>

      <BModal open={detailsOpen} onClose={() => setDetailsOpen(false)} title={t('Ongeki.RecentPage.Details')}>
        <table className="judge-table table table-borderless table-sm table-striped table-dark align-middle">
          <tbody>
            <tr>
              <td className="combo">COMBO</td>
              <td className="combo">{playLog.maxCombo}</td>
            </tr>
            <tr>
              <td className="critical-break">C.BREAK</td>
              <td className="critical-break">{playLog.judgeCriticalBreak}</td>
            </tr>
            <tr>
              <td className="break">BREAK</td>
              <td className="break">{playLog.judgeBreak}</td>
            </tr>
            <tr>
              <td className="hit">HIT</td>
              <td className="hit">{playLog.judgeHit}</td>
            </tr>
            <tr>
              <td className="miss">MISS</td>
              <td className="miss">{playLog.judgeMiss}</td>
            </tr>
            <tr>
              <td className="bell">BELL</td>
              <td className="bell">
                {playLog.bellCount}/{playLog.totalBellCount}
              </td>
            </tr>
            <tr>
              <td className="damage">DAMAGE</td>
              <td className="damage">{playLog.damageCount}</td>
            </tr>
            <tr>
              <td>TAP</td>
              <td>{playLog.rateTap}%</td>
            </tr>
            <tr>
              <td>HOLD</td>
              <td>{playLog.rateHold}%</td>
            </tr>
            <tr>
              <td>FLICK</td>
              <td>{playLog.rateFlick}%</td>
            </tr>
            <tr>
              <td>SIDE TAP</td>
              <td>{playLog.rateSideTap}%</td>
            </tr>
            <tr>
              <td>SIDE HOLD</td>
              <td>{playLog.rateSideHold}%</td>
            </tr>
          </tbody>
        </table>
      </BModal>

      <OngekiSongScoreRanking
        music={rankingMusic}
        open={!!rankingMusic}
        onClose={() => setRankingMusic(null)}
      />
    </div>
  );
}

export const __unusedDifficulty = Difficulty;

// src/app/sega/ongeki/ongeki-recent-item/ongeki-recent-item.component.ts
import {Component, OnInit} from '@angular/core';
import {PlayerPlaylog} from '../model/PlayerPlaylog';
import {AttributeType, BattleRank, Difficulty, TechnicalRank} from '../model/OngekiEnums';
import {environment} from '../../../../environments/environment';
import {NgbModal, NgbOffcanvas} from '@ng-bootstrap/ng-bootstrap';
import {Router} from '@angular/router';
import {OngekiMusic} from '../model/OngekiMusic';
import {OngekiSongScoreRankingComponent} from '../ongeki-song-score-ranking/ongeki-song-score-ranking.component';

@Component({
  selector: 'app-ongeki-recent-item',
  templateUrl: './ongeki-recent-item.component.html',
  styleUrls: ['./ongeki-recent-item.component.css'],
  inputs: ['playLog']
})
export class OngekiRecentItemComponent implements OnInit {
  playLog: PlayerPlaylog;
  host = environment.assetsHost;
  difficulty = Difficulty;
  battleRank = BattleRank;
  technicalRank = TechnicalRank;
  attributeType = AttributeType;
  isCollapsed = false;
  protected readonly Difficulty = Difficulty;
  protected readonly Math = Math;

  constructor(
    private modalService: NgbModal,
    public router: Router,
    private offcanvasService: NgbOffcanvas,
  ) { }

  ngOnInit(): void {
  }
  open(content) {
    this.modalService.open(content, {  centered: true  });
  }

  showDetail(music: OngekiMusic) {
    const offcanvasRef = this.offcanvasService.open(OngekiSongScoreRankingComponent, {
      position: 'end',
      scroll: false,
    });
    offcanvasRef.componentInstance.music = music;
  }

  getArrayFromNumber(n: number): any[] {
    return new Array(n);
  }
}

<div class="card">
  <div class="song-info card-header hstack gap-2">
    <div class="jacket-container ratio ratio-1x1">
      <!--jacket-->
      <img class="jacket"
        src="{{host}}assets/ongeki/jacket/UI_Jacket_{{playLog.musicId|formatNumber:4}}.webp"
        alt="">
      </div>
      <div class="overflow-hidden">
        <!--title-->
        <div class="song-info-title text-truncate fw-bold">
          <span>
            {{ playLog.songInfo != null ? playLog.songInfo.name : 'MusicID:' + playLog.musicId }}
          </span>
        </div>
        <!--artist-->
        <div class="song-info-artist text-truncate ">
          <span>
            {{ playLog.songInfo != null ? playLog.songInfo.artistName : ('Ongeki.RecentPage.UnknownArtist' | translate) }}
          </span>
        </div>
        <!--difficulty-->
        <div>
          @switch (difficulty[playLog.level]) {
            @case ('Basic') {
              <span
                class="difficulty difficulty-basic badge rounded-pill">
                Basic
                {{ ($safeNavigationMigration(playLog.songInfo?.level0) | toLevelDecimal) ?? 'None' }}
              </span>
            }
            @case ('Advanced') {
              <span
                class="difficulty difficulty-advanced badge rounded-pill">
                Advanced
                {{ ($safeNavigationMigration(playLog.songInfo?.level1) | toLevelDecimal) ?? 'None' }}
              </span>
            }
            @case ('Expert') {
              <span
                class="difficulty difficulty-expert badge rounded-pill">
                Expert
                {{ ($safeNavigationMigration(playLog.songInfo?.level2) | toLevelDecimal) ?? 'None' }}
              </span>
            }
            @case ('Master') {
              <span
                class="difficulty difficulty-master badge rounded-pill">
                Master
                {{ ($safeNavigationMigration(playLog.songInfo?.level3) | toLevelDecimal) ?? 'None' }}
              </span>
            }
            @case ('Lunatic') {
              <span
                class="difficulty difficulty-lunatic badge rounded-pill">
                Lunatic
                {{ ($safeNavigationMigration(playLog.songInfo?.level4) | toLevelDecimal) ?? 'None' }}
              </span>
            }
          }
        </div>
      </div>
    </div>
    <div class="play-result card-body ">
      <div class="row align-items-center">
        <div class="score-area col-12 col-md-6">
          <div class="row text-nowrap">
            <div class="col-6 col-sm-3 col-md-6 col-lg-3 text-end">
              <!--battle score-->
              <div class="item-header battle-item-header">
                <span>BATTLE SCORE</span>
              </div>
              <div class="score" [class.new-record]="playLog.isBattleNewRecord">
                <span class="score-font-large">{{ Math.floor(playLog.battleScore / 10000) }}</span>
                <span class="score-font-small">{{ playLog.battleScore % 10000|formatNumber:4 }}</span>
              </div>
              <!--over damage-->
              <div class="item-header battle-item-header">
                <span>OVER DAMAGE</span>
              </div>
              <div class="score" [class.new-record]="playLog.isOverDamageNewRecord">
                <span class="score-font-large">{{ Math.floor(playLog.overDamage / 100) }}</span>
                <span class="score-font-small">.{{ playLog.overDamage % 100|formatNumber:2 }}%</span>
              </div>
            </div>
            <!--score stamp-->
            <div class="col-6 col-sm-3 col-md-6 col-lg-3 align-items-center d-flex">
              <img class="score-stamp" src="{{host}}assets/ongeki/gameUi/{{playLog.battleScoreRank | toBattleSprite}}"
                alt="{{battleRank[playLog.battleScoreRank]}}">
              </div>
              <div class="col-6 col-sm-3 col-md-6 col-lg-3 text-end">
                <!--technical score-->
                <div class="item-header technical-item-header">
                  <span>TECHNICAL SCORE</span>
                </div>
                <div class="score" [class.new-record]="playLog.isTechNewRecord">
                  <span class="score-font-large">{{ Math.floor(playLog.techScore / 10000) }}</span>
                  <span class="score-font-small">{{ playLog.techScore % 10000|formatNumber:4 }}</span>
                </div>
                <!--platinum-->
                <ng-container>
                  <div class="item-header technical-item-header">
                    <span>PLATINUM</span>
                  </div>
                  <div class="score">
                    <div class="platinum-star-container">
                      @for (_ of getArrayFromNumber(playLog.platinumScoreStar); track _) {
                        <img
                          class="platinum-star" src="{{host}}assets/ongeki/gameUi/UI_Card_star_00.webp">
                        }
                        @for (_ of getArrayFromNumber(5 - playLog.platinumScoreStar); track _) {
                          <img
                            class="platinum-star" src="{{host}}assets/ongeki/gameUi/UI_Card_star_01.webp">
                          }
                        </div>
                        <div class="score-font-large platinum-score">{{ playLog.platinumScore }}</div>
                      </div>
                    </ng-container>
                  </div>
                  <!--score rank-->
                  <div class="col-6 col-sm-3 col-md-6 col-lg-3 align-items-center d-flex" style="max-width: 150px">
                    <img class="score-stamp"
                      src="{{host}}assets/ongeki/gameUi/{{playLog.techScoreRank | toTechSprite}}"
                      alt="{{technicalRank[playLog.techScoreRank]}}">
                    </div>
                  </div>
                  <div class="row row-cols-2 align-items-center">
                    <!--full bell-->
                    <div class="col-6 col-sm-auto col-md-6 col-xl-auto text-end">
                      <img class="score-honor" alt=""
                        src="{{host}}assets/ongeki/gameUi/UI_RES_Score_FB_{{playLog.isFullBell ? 'Badge' : 'Base'}}.webp">
                      </div>
                      <!--all break-->
                      <div class="col-6 col-sm-auto col-md-6 col-xl-auto text-start">
                        <img class="score-honor" alt=""
                          src="{{host}}assets/ongeki/gameUi/UI_RES_Score_{{playLog.isAllBreak ? 'AB' : 'FC'}}_{{playLog.isFullCombo ? 'Badge' : 'Base'}}.webp">
                        </div>
                      </div>
                    </div>
                    <div class="col-12 col-md-6">
                      <div class="battle-area row">
                        <div class="col-6">
                          <div class="chara-container">
                            <div class="chara-center position-relative">
                              <img class="chara-center-img position-absolute"
                                src="{{host}}assets/ongeki/card-icon/UI_Card_Icon_{{playLog.cardInfo2?.id??0 | formatNumber:6}}.webp">
                                <app-ongeki-card-level class="chara-center-level position-absolute"
                                  [level]="playLog.cardLevel2"
                                [attribute]="playLog.cardInfo2?.attribute??'Fire'"></app-ongeki-card-level>
                              </div>
                              <div class="chara-side position-relative">
                                <img class="chara-side-img position-absolute"
                                  src="{{host}}assets/ongeki/card-icon/UI_Card_Icon_{{playLog.cardInfo1?.id??0 | formatNumber:6}}.webp">
                                  <app-ongeki-card-level class="chara-side-level position-absolute"
                                    [level]="playLog.cardLevel1"
                                  [attribute]="playLog.cardInfo1?.attribute??'Fire'"></app-ongeki-card-level>
                                </div>
                                <div class="chara-side position-relative">
                                  <img class="chara-side-img position-absolute"
                                    src="{{host}}assets/ongeki/card-icon/UI_Card_Icon_{{playLog.cardInfo3?.id??0 | formatNumber:6}}.webp">
                                    <app-ongeki-card-level class="chara-side-level position-absolute"
                                      [level]="playLog.cardLevel3"
                                    [attribute]="playLog.cardInfo3?.attribute??'Fire'"></app-ongeki-card-level>
                                  </div>
                                </div>
                              </div>
                              <div class="col-6">
                                <div class="boss position-relative">
                                  <img class="boss-img"
                                    alt=""
                                    src="{{host}}assets/ongeki/card-chara/UI_Card_Chara_{{playLog.songInfo?.bossCardId??0 | formatNumber:6}}.webp">
                                    <app-ongeki-card-level class="boss-level position-absolute"
                                      [level]="playLog.bossLevel"
                                    [attribute]="attributeType[playLog?.bossAttribute]"></app-ongeki-card-level>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="card-footer fw-bold">
                          <div class="float-start">
                            <a type="button" class="text-primary"
                            (click)="open(judgeContent)">{{ 'Ongeki.RecentPage.Details' | translate }}</a>
                          </div>
                          <div class="float-start ms-3">
                            <a type="button" class="text-primary"
                            (click)="showDetail(playLog.songInfo)">{{ 'Ongeki.RecentPage.Ranking' | translate }}</a>
                          </div>
                          <div class="float-end">
                            <span>{{ (playLog.userPlayDate | toDate).toLocaleString() }}</span>
                          </div>
                        </div>
                      </div>

                      <ng-template #judgeContent let-modal>
                        <div class="modal-header">
                          <h4 class="modal-title">{{ 'Ongeki.RecentPage.Details' | translate }}</h4>
                          <button type="button" class="btn-close shadow-none" aria-label="Close" (click)="modal.dismiss()"></button>
                        </div>
                        <div class="modal-body">
                          <table class="judge-table table table-borderless table-sm table-striped table-dark align-middle">
                            <tbody>
                              <tr>
                                <td class="combo">COMBO</td>
                                <td class="combo">{{ playLog.maxCombo }}</td>
                              </tr>
                              <tr>
                                <td class="critical-break">C.BREAK</td>
                                <td class="critical-break">{{ playLog.judgeCriticalBreak }}</td>
                              </tr>
                              <tr>
                                <td class="break">BREAK</td>
                                <td class="break">{{ playLog.judgeBreak }}</td>
                              </tr>
                              <tr>
                                <td class="hit">HIT</td>
                                <td class="hit">{{ playLog.judgeHit }}</td>
                              </tr>
                              <tr>
                                <td class="miss">MISS</td>
                                <td class="miss">{{ playLog.judgeMiss }}</td>
                              </tr>
                              <tr>
                                <td class="bell">BELL</td>
                                <td class="bell">{{ playLog.bellCount }}/{{ playLog.totalBellCount }}</td>
                              </tr>
                              <tr>
                                <td class="damage">DAMAGE</td>
                                <td class="damage">{{ playLog.damageCount }}</td>
                              </tr>
                              <tr>
                                <td>TAP</td>
                                <td>{{ playLog.rateTap }}%</td>
                              </tr>
                              <tr>
                                <td>HOLD</td>
                                <td>{{ playLog.rateHold }}%</td>
                              </tr>
                              <tr>
                                <td>FLICK</td>
                                <td>{{ playLog.rateFlick }}%</td>
                              </tr>
                              <tr>
                                <td>SIDE TAP</td>
                                <td>{{ playLog.rateSideTap }}%</td>
                              </tr>
                              <tr>
                                <td>SIDE HOLD</td>
                                <td>{{ playLog.rateSideHold }}%</td>
                              </tr>
                            </tbody>
                          </table>
                        </div>
                      </ng-template>
