// src/features/ongeki/OngekiSongScoreRanking.tsx
import { useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Sheet, SheetClose, SheetContent } from '@/components/ui/sheet';
import { StopFill } from 'react-bootstrap-icons';
import { api } from '@/lib/api/client';
import { notice } from '@/lib/message';
import { dbGetByKey } from '@/lib/db/db';
import { getCurrentUser } from '@/lib/user';
import { assetsHost, enableImages } from '@/lib/utils';
import { fullWidth, ordinal, padDigits } from '@/lib/format';
import { toLevelDecimal, toTechHonorSprite } from './pipes';
import { OngekiCardLevel } from './OngekiCardLevel';
import type { OngekiCard, OngekiMusic } from './models';
import '@/styles/song-detail.css';
import './song-score-ranking.css';

interface Ranking {
  level?: number;
  username: string;
  score: number;
}

interface ISongData {
  musicId: number;
  level: number;
  playCount: number;
  techScoreMax: number;
  techScoreRank: number;
  battleScoreMax: number;
  battleScoreRank: number;
  platinumScoreMax: number;
  maxComboCount: number;
  maxOverKill: number;
  maxTeamOverKill: number;
  clearStatus: number;
  storyWatched: boolean;
  isFullBell: boolean;
  isFullCombo: boolean;
  isAllBreake: boolean;
  isLock: boolean;
  ranking?: { rank: number; playedCount: number };
}

const SHEET_EXIT_DURATION_MS = 300;

function isLunatic(song: OngekiMusic): boolean {
  return (
    song.level0 === '0,0' && song.level1 === '0,0' && song.level2 === '0,0' && song.level3 === '0,0'
  );
}

function getLevelString(song: OngekiMusic, level: number): string {
  if (!song) return '0';
  if (level === 0) return song.level0;
  else if (level === 1) return song.level1;
  else if (level === 2) return song.level2;
  else if (level === 3) return song.level3;
  else if (level === 10) return song.level4;
  return '0';
}

const DIFF_META: Record<number, { name: string; color: string; lunatic?: boolean }> = {
  0: { name: 'Basic', color: 'color-basic' },
  1: { name: 'Advanced', color: 'color-advanced' },
  2: { name: 'Expert', color: 'color-expert' },
  3: { name: 'Master', color: 'color-master' },
  10: { name: 'Lunatic', color: '', lunatic: true },
};

/** 等价旧版 ongeki-song-score-ranking.component（成绩排名 offcanvas） */
export function OngekiSongScoreRanking({
  music: selectedMusic,
  open,
  onClose,
}: {
  music: OngekiMusic | null;
  open: boolean;
  onClose: () => void;
}) {
  const { t } = useTranslation();
  const [renderedMusic, setRenderedMusic] = useState<OngekiMusic | null>(selectedMusic);
  const [sheetOpen, setSheetOpen] = useState(open);
  const closeTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const music = selectedMusic ?? renderedMusic;
  const [ranking, setRanking] = useState<Ranking[]>([]);
  const [songData, setSongData] = useState<Record<number, ISongData> | null>(null);
  const [loadingSongData, setLoadingSongData] = useState(true);
  const [bossCard, setBossCard] = useState<OngekiCard | null>(null);
  const [activeTab, setActiveTab] = useState<number>(3);

  useEffect(() => {
    if (selectedMusic) setRenderedMusic(selectedMusic);
  }, [selectedMusic]);

  useEffect(() => {
    if (open) {
      if (closeTimerRef.current) {
        clearTimeout(closeTimerRef.current);
        closeTimerRef.current = null;
      }
      setSheetOpen(true);
    } else {
      setSheetOpen(false);
    }
  }, [open]);

  useEffect(
    () => () => {
      if (closeTimerRef.current) clearTimeout(closeTimerRef.current);
    },
    [],
  );

  function requestClose() {
    if (closeTimerRef.current) return;
    setSheetOpen(false);
    closeTimerRef.current = setTimeout(() => {
      closeTimerRef.current = null;
      onClose();
    }, SHEET_EXIT_DURATION_MS);
  }

  useEffect(() => {
    if (!music || !open) return;
    setSongData(null);
    setLoadingSongData(true);
    setActiveTab(isLunatic(music) ? 10 : 3);

    void dbGetByKey<OngekiCard>('ongekiCard', music.bossCardId).then((x) => x && setBossCard(x));

    const aimeId = String(getCurrentUser()?.defaultCard?.extId ?? '');
    void api
      .get(`api/game/ongeki/song/${music.id}`, { aimeId })
      .then((res) => {
        const data: Record<number, ISongData> = {};
        for (const d of res ?? []) {
          data[d.level] = d;
        }
        setSongData(data);
        setLoadingSongData(false);
      })
      .catch(() => {
        notice(t('Common.FailedToLoad'), 'danger');
        setLoadingSongData(false);
      });

    void api
      .get('api/game/ongeki/musicScoreRanking', {
        musicId: music.id,
        level: isLunatic(music) ? 10 : 3,
      })
      .then((res) => setRanking(res ?? []));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [music, open]);

  function handleTabButtonClick(level: number) {
    if (!music) return;
    setActiveTab(level);
    void api
      .get('api/game/ongeki/musicScoreRanking', { musicId: music.id, level })
      .then((res) => setRanking(res ?? []));
  }

  if (!music) return null;
  const lunatic = isLunatic(music);

  const difficultyDetail = (difficulty: number) => {
    const meta = DIFF_META[difficulty];
    const data = songData?.[difficulty];
    return (
      <div className="card my-2" key={difficulty}>
        <div
          className={
            'card-header py-1 px-2 text-truncate' +
            (meta.lunatic ? ' border border-danger bg-lunatic text-danger' : '')
          }
        >
          <div className="hstack">
            <StopFill className={(meta.lunatic ? '' : meta.color) + ' h-100 d-flex align-items-center'} />
            <div className="p-0 align-middle ps-1 small">
              {meta.name} {toLevelDecimal(getLevelString(music, difficulty))}
            </div>
          </div>
        </div>
        <div className="card-body py-1 px-3">
          <div className="difficulty-detail-body d-flex align-items-center justify-content-between">
            <div className="float-start small fw-bold">
              {data ? (
                <>
                  <div>{data.techScoreMax}</div>
                  <div className="small text-secondary">
                    {t('Ongeki.MusicList.SongScoreRanking.PlayCount')}
                    {t('Common.Colon')}
                    {data.playCount}
                  </div>
                </>
              ) : (
                <div>No Record</div>
              )}
            </div>
            {data && (
              <div className="honor float-end">
                <img
                  className="honor-badge"
                  src={assetsHost + `assets/ongeki/gameUi/${toTechHonorSprite(data.techScoreRank)}`}
                  alt=""
                />
                {data.isAllBreake ? (
                  <img
                    className="honor-badge"
                    src={assetsHost + 'assets/ongeki/gameUi/UI_SLC_MusicSelect_HornorBadge_AB.webp'}
                    alt=""
                  />
                ) : data.isFullCombo ? (
                  <img
                    className="honor-badge"
                    src={assetsHost + 'assets/ongeki/gameUi/UI_SLC_MusicSelect_HornorBadge_FC.webp'}
                    alt=""
                  />
                ) : (
                  <img
                    className="honor-badge"
                    src={assetsHost + 'assets/ongeki/gameUi/UI_SLC_MusicSelect_HornorBadge_None.webp'}
                    alt=""
                  />
                )}
                <img
                  className="honor-badge"
                  src={
                    assetsHost +
                    `assets/ongeki/gameUi/UI_SLC_MusicSelect_HornorBadge_${data.isFullBell ? 'FB' : 'None'}.webp`
                  }
                  alt=""
                />
              </div>
            )}
          </div>
        </div>
      </div>
    );
  };

  const rankingTable = (playerRanking?: { rank: number; playedCount: number }) => (
    <>
      {playerRanking && (
        <div className="callout callout-info mt-2 mb-1">
          {t('Ongeki.MusicList.SongScoreRanking.RankingInfo', {
            ranking: ordinal(playerRanking.rank),
            total: playerRanking.playedCount,
          })}
        </div>
      )}
      <table className="table table-striped table-borderless mb-0">
        <thead>
          <tr>
            <th>No.</th>
            <th>Username</th>
            <th>Score</th>
          </tr>
        </thead>
        <tbody>
          {ranking.map((item, i) => (
            <tr key={i}>
              <td>
                {i === 0 && <img className="medal" src={assetsHost + 'assets/gold-medal.svg'} alt="" />}
                {i === 1 && <img className="medal" src={assetsHost + 'assets/silver-medal.svg'} alt="" />}
                {i === 2 && <img className="medal" src={assetsHost + 'assets/bronze-medal.svg'} alt="" />}
                {i > 2 && <span>{i + 1}</span>}
              </td>
              <td>{fullWidth(item.username)}</td>
              <td>{item.score}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </>
  );

  const tabs = lunatic ? [10] : [0, 1, 2, 3];
  const tabName: Record<number, string> = { 0: 'BA', 1: 'AD', 2: 'EX', 3: 'MA', 10: 'LUNATIC' };

  return (
    <Sheet
      open={sheetOpen}
      onOpenChange={(v) => {
        if (v) {
          if (closeTimerRef.current) {
            clearTimeout(closeTimerRef.current);
            closeTimerRef.current = null;
          }
          setSheetOpen(true);
        } else {
          requestClose();
        }
      }}
    >
      <SheetContent
        side="right"
        showCloseButton={false}
        className="song-detail-surface ongeki-song-score-ranking ongeki-song-score-ranking-sheet z-[1045] w-[400px] max-w-full sm:max-w-[400px] p-0 text-sm bg-[var(--bs-body-bg)] outline-none"
        overlayClassName="ongeki-song-score-ranking-overlay"
      >
        <div className="offcanvas-header position-absolute end-0 z-3">
          <SheetClose asChild>
            <button type="button" className="btn-close" aria-label="Close" />
          </SheetClose>
        </div>
        <SheetClose asChild>
          <button type="button" className="btn-close song-detail-modern-close" aria-label="Close" />
        </SheetClose>
        <div className="offcanvas-body pt-0 px-0">
          <div
            className="music-info-container row pb-3 pt-3 gap-3 px-3 m-0"
            style={
              {
                '--jacket-img': `url(${assetsHost}assets/ongeki/jacket/UI_Jacket_${padDigits(music.id, 4)}.webp)`,
              } as React.CSSProperties
            }
          >
            <div className="col-12 p-0">
              {enableImages && (
                <img
                  className="music-img"
                  src={assetsHost + `assets/ongeki/jacket/UI_Jacket_${padDigits(music.id, 4)}.webp`}
                  alt=""
                />
              )}
            </div>
            <div className="col-12 music-info">
              <h4 className="music-title">{music.name}</h4>
              <div className="mb-1">{music.artistName}</div>
              <div className="text-secondary">{music.genre}</div>
            </div>
          </div>

          {bossCard && (
            <>
              <hr className="mt-0" />
              <div className="mx-3">
                <section className="mb-2">
                  <h3 className="mb-3">{t('Ongeki.MusicList.SongScoreRanking.Boss')}</h3>
                  <div className="d-flex align-items-end">
                    <img
                      className="boss-img"
                      src={
                        assetsHost +
                        `assets/ongeki/card-icon/UI_Card_Icon_${padDigits(bossCard.id, 6)}_S.webp`
                      }
                      alt=""
                    />
                    <OngekiCardLevel
                      className="boss-level"
                      level={music.bossLevel}
                      attribute={bossCard.attribute ?? ''}
                    />
                  </div>
                </section>
              </div>
            </>
          )}

          {loadingSongData && (
            <>
              <hr />
              <div className="text-center">
                <div className="spinner-border" role="status">
                  <span className="visually-hidden">Loading...</span>
                </div>
              </div>
            </>
          )}
          {!loadingSongData && !songData && (
            <>
              <hr />
              <div className="mx-3">
                <section className="mb-3">
                  <h3 className="mb-3">{t('Ongeki.MusicList.SongScoreRanking.Details')}</h3>
                  <div className="alert alert-danger" role="alert">
                    {t('Common.FailedToLoad')}
                  </div>
                </section>
              </div>
            </>
          )}
          {songData && (
            <>
              <hr />
              <div className="mx-3">
                <section className="mb-3">
                  <h3 className="mb-3">{t('Ongeki.MusicList.SongScoreRanking.Details')}</h3>
                  {(lunatic ? [10] : [0, 1, 2, 3]).map((d) => difficultyDetail(d))}
                </section>
              </div>
              <hr />
              <div className="mx-3">
                <h3>{t('Ongeki.MusicList.SongScoreRanking.Ranking')}</h3>
                <nav>
                  <div className="nav nav-tabs" id="nav-tab" role="tablist">
                    {tabs.map((level) => (
                      <button
                        key={level}
                        className={'nav-link' + (activeTab === level ? ' active' : '')}
                        type="button"
                        role="tab"
                        onClick={() => handleTabButtonClick(level)}
                      >
                        {tabName[level]}
                      </button>
                    ))}
                  </div>
                </nav>
                <div className="tab-content">
                  <div className="tab-pane fade show active">
                    {rankingTable(songData[activeTab]?.ranking)}
                  </div>
                </div>
              </div>
            </>
          )}
        </div>
      </SheetContent>
    </Sheet>
  );
}

// src/app/sega/ongeki/ongeki-song-score-ranking/ongeki-song-score-ranking.component.ts
import {Component, Input} from '@angular/core';
import { ApiService } from '../../../api.service';
import { MessageService } from '../../../message.service';
import {OngekiMusic} from '../model/OngekiMusic';
import {environment} from '../../../../environments/environment';
import {NgbOffcanvas} from '@ng-bootstrap/ng-bootstrap';
import { HttpParams } from '@angular/common/http';
import { UserService } from 'src/app/user.service';
import {NgxIndexedDBService} from 'ngx-indexed-db';
import {OngekiCard} from '../model/OngekiCard';
import {TranslateService} from '@ngx-translate/core';

interface Ranking {
  level?: number;
  username: string;
  score: number;
}

interface ISongData {
  musicId: number;
  level: number;
  playCount: number;
  techScoreMax: number;
  techScoreRank: number;
  battleScoreMax: number;
  battleScoreRank: number;
  platinumScoreMax: number;
  maxComboCount: number;
  maxOverKill: number;
  maxTeamOverKill: number;
  clearStatus: number;
  storyWatched: boolean;
  isFullBell: boolean;
  isFullCombo: boolean;
  isAllBreake: boolean;
  isLock: boolean;
  ranking: UserRanking;
}

interface UserRanking {
  rank: number;
  playedCount: number;
}

@Component({
  selector: 'app-ongeki-song-score-ranking',
  templateUrl: './ongeki-song-score-ranking.component.html',
  styleUrls: ['./ongeki-song-score-ranking.component.css', ]
})
export class OngekiSongScoreRankingComponent {
  protected readonly Math = Math;
  ranking: Ranking[];
  songData: {[key: number]: ISongData};
  loadingSongData = true;
  host = environment.assetsHost;
  protected readonly parseFloat = parseFloat;
  @Input() public music: OngekiMusic;
  protected bossCard: OngekiCard;
  constructor(
    private dbService: NgxIndexedDBService,
    private api: ApiService,
    private userService: UserService,
    private translate: TranslateService,
    public messageService: MessageService,
    public offcanvasService: NgbOffcanvas,
  ) {
  }

  ngOnInit() {
    this.dbService.getByID<OngekiCard>('ongekiCard', this.music.bossCardId).subscribe((x) => {
      this.bossCard = x;
    });

    const { id } = this.music;
    this.api.get(`api/game/ongeki/song/${id}?aimeId=${String(this.userService.currentUser.defaultCard.extId)}`).subscribe({
      next: (res) => {
        const songData = {};
        for (const data of res) {
          songData[data.level] = data;
        }
        this.songData = songData;
        this.loadingSongData = false;
      },
      error: (err) => {
        this.translate.get('Common.FailedToLoad').subscribe((res: string) => {
          this.messageService.notice(res, 'danger');
        });
        this.loadingSongData = false;
      }
    }
    );

    if (!this.isLunatic(this.music)){
      const param = new HttpParams().set('musicId', id).set('level', 3);
      this.api.get('api/game/ongeki/musicScoreRanking', param).subscribe((res) => {
        this.ranking = res;
      });
    }
    else{
      const param = new HttpParams().set('musicId', id).set('level', 10);
      this.api.get('api/game/ongeki/musicScoreRanking', param).subscribe((res) => {
        this.ranking = res;
      });
    }


  }

  getMaxBattleScore(songData: { [key: number]: ISongData }): number {
    const scores = Object.values(songData).map(song => song.battleScoreMax);
    return scores.length > 0 ? Math.max(...scores) : 0;
  }

  handleTabButtonClick(level: number) {
    const { id } = this.music;
    const param = new HttpParams().set('musicId', id).set('level', level);
    this.api.get('api/game/ongeki/musicScoreRanking', param).subscribe(
      res => {
        this.ranking = res;
      }
    );
  }

  isLunatic(song: OngekiMusic) {
    return song.level0 === '0,0' &&
      song.level1 === '0,0' &&
      song.level2 === '0,0' &&
      song.level3 === '0,0';
  }

  getLevelString(song: OngekiMusic, level: number) {
    if (!song) { return '0'; }
    if (level === 0){
      return song.level0;
    }
    else if (level === 1){
      return song.level1;
    }
    else if (level === 2){
      return song.level2;
    }
    else if (level === 3){
      return song.level3;
    }
    else if (level === 10){
      return song.level4;
    }
    else { return '0'; }
  }

  battleScoreRank(score: number) {
    switch (true) {
      case (score >= 1007500):
        return 'SSS+';
      case score >= 1000000 && score <= 1007499:
        return 'SSS';
      case score >= 990000 && score <= 999999:
        return 'SS';
      case score >= 970000 && score <= 989999:
        return 'S';
      case score >= 940000 && score <= 969999:
        return 'AAA';
      case score >= 900000 && score <= 939999:
        return 'AA';
      case score >= 850000 && score <= 899999:
        return 'A';
      case score >= 800000 && score <= 849999:
        return 'BBB';
      case score >= 750000 && score <= 799999:
        return 'BB';
      case score >= 700000 && score <= 749999:
        return 'B';
      case score >= 500000 && score <= 699999:
        return 'C';
      case score >= 0 && score <= 499999:
        return 'D';
    }
  }
}

<div class="offcanvas-header position-absolute end-0 z-3">
  <button type="button" class="btn-close" (click)="offcanvasService.dismiss()"></button>
</div>
<div class="offcanvas-body pt-0 px-0">
  <div class="music-info-container row pb-3 pt-3 gap-3 px-3 m-0"
       [style.--jacket-img]="'url(' + host + 'assets/ongeki/jacket/UI_Jacket_' + (music.id|formatNumber:4) + '.webp)'">
    <div class="col-12 p-0">
      <img class="music-img"
           src="{{host}}assets/ongeki/jacket/UI_Jacket_{{music.id|formatNumber:4}}.webp"
           alt="">
    </div>
    <div class="col-12 music-info">
      <h4 class="music-title">{{ music.name }}</h4>
      <div class="mb-1">{{ music.artistName }}</div>
      <div class="text-secondary">{{ music.genre }}</div>
    </div>
  </div>

  <ng-container *ngIf="bossCard">
    <hr class="mt-0">
    <div class="mx-3">
      <section class="mb-2">
        <h3 class="mb-3">{{ "Ongeki.MusicList.SongScoreRanking.Boss" | translate }}</h3>
        <div class="d-flex align-items-end">
          <img class="boss-img"
               src="{{host}}assets/ongeki/card-icon/UI_Card_Icon_{{bossCard.id | formatNumber:6}}_S.webp">
          <app-ongeki-card-level class="boss-level"
                                 [level]="music.bossLevel"
                                 [attribute]="bossCard.attribute??''"></app-ongeki-card-level>
        </div>
      </section>
    </div>
  </ng-container>

  <ng-container *ngIf="loadingSongData">
    <hr>
    <div class="text-center">
      <div class="spinner-border" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
    </div>
  </ng-container>
  <ng-container *ngIf="!loadingSongData && !songData">
    <hr>
    <div class="mx-3">
      <section class="mb-3">
        <h3 class="mb-3">{{ "Ongeki.MusicList.SongScoreRanking.Details" | translate }}</h3>
        <div class="alert alert-danger" role="alert">
          {{ "Common.FailedToLoad" | translate }}
        </div>
      </section>
    </div>
  </ng-container>
  <ng-container *ngIf="songData">
    <hr>
    <div class="mx-3">
      <section class="mb-3">
        <h3 class="mb-3">{{ "Ongeki.MusicList.SongScoreRanking.Details" | translate }}</h3>
        <ng-container *ngIf="!isLunatic(music) && songData">
          <ng-container *ngTemplateOutlet="difficultyDetail; context: {$implicit: 0}"></ng-container>
          <ng-container *ngTemplateOutlet="difficultyDetail; context: {$implicit: 1}"></ng-container>
          <ng-container *ngTemplateOutlet="difficultyDetail; context: {$implicit: 2}"></ng-container>
          <ng-container *ngTemplateOutlet="difficultyDetail; context: {$implicit: 3}"></ng-container>
        </ng-container>
        <ng-container *ngIf="isLunatic(music) && songData">
          <ng-container *ngTemplateOutlet="difficultyDetail; context: {$implicit: 10}"></ng-container>
        </ng-container>
      </section>
    </div>
    <hr>
    <div class="mx-3">
      <h3>{{ "Ongeki.MusicList.SongScoreRanking.Ranking" | translate }}</h3>
      <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
          <ng-container *ngIf="music.id < 8e3 && songData">
            <button class="nav-link" id="nav-ba-tab" (click)="handleTabButtonClick(0)" data-bs-toggle="tab"
                    data-bs-target="#nav-ba" type="button" role="tab" aria-controls="nav-ba" aria-selected="false">BA
            </button>
            <button class="nav-link" id="nav-ad-tab" (click)="handleTabButtonClick(1)" data-bs-toggle="tab"
                    data-bs-target="#nav-ad" type="button" role="tab" aria-controls="nav-ad" aria-selected="false">AD
            </button>
            <button class="nav-link" id="nav-ex-tab" (click)="handleTabButtonClick(2)" data-bs-toggle="tab"
                    data-bs-target="#nav-ex" type="button" role="tab" aria-controls="nav-ex" aria-selected="false">EX
            </button>
            <button class="nav-link active" id="nav-ma-tab" (click)="handleTabButtonClick(3)" data-bs-toggle="tab"
                    data-bs-target="#nav-ma" type="button" role="tab" aria-controls="nav-ma" aria-selected="true">MA
            </button>
          </ng-container>
          <ng-container *ngIf="music.id > 8e3 && songData">
            <button class="nav-link  active" id="nav-lu-tab" (click)="handleTabButtonClick(10)" data-bs-toggle="tab"
                    data-bs-target="#nav-lu" type="button" role="tab" aria-controls="nav-lu" aria-selected="true">LUNATIC
            </button>
          </ng-container>
        </div>
      </nav>
      <div class="tab-content" id="nav-tabContent">
        <ng-container *ngIf="music.id < 8e3 && songData">
          <div class="tab-pane fade" id="nav-ba" role="tabpanel" aria-labelledby="nav-ba-tab" tabindex="0">
            <ng-container *ngTemplateOutlet="rankingTable;context: {playerRanking: $safeNavigationMigration(songData[0]?.ranking)}"/>
          </div>
          <div class="tab-pane fade" id="nav-ad" role="tabpanel" aria-labelledby="nav-ad-tab" tabindex="0">
            <ng-container *ngTemplateOutlet="rankingTable;context: {playerRanking: $safeNavigationMigration(songData[1]?.ranking)}"/>
          </div>
          <div class="tab-pane fade" id="nav-ex" role="tabpanel" aria-labelledby="nav-ex-tab" tabindex="0">
            <ng-container *ngTemplateOutlet="rankingTable;context: {playerRanking: $safeNavigationMigration(songData[2]?.ranking)}"/>
          </div>
          <div class="tab-pane fade show active" id="nav-ma" aria-labelledby="nav-ma-tab" tabindex="0">
            <ng-container *ngTemplateOutlet="rankingTable;context: {playerRanking: $safeNavigationMigration(songData[3]?.ranking)}"/>
          </div>
        </ng-container>
        <ng-container *ngIf="music.id > 8e3 && songData">
          <div class="tab-pane fade show active" id="nav-ma" aria-labelledby="nav-ma-tab" tabindex="0">
            <ng-container *ngTemplateOutlet="rankingTable;context: {playerRanking: $safeNavigationMigration(songData[10]?.ranking)}"/>
          </div>
        </ng-container>
      </div>
    </div>
  </ng-container>
</div>

<ng-template #difficultyDetail let-difficulty>
  <div class="card my-2">
    <ng-container [ngSwitch]="difficulty">
      <div *ngSwitchCase="0" class="card-header py-1 px-2 text-truncate">
        <div class="hstack">
          <ng-icon name="bootstrap-stop-fill" class="color-basic h-100 d-flex align-items-center"></ng-icon>
          <div class="p-0 align-middle ps-1 small">
            Basic
            {{ getLevelString(music, difficulty) | toLevelDecimal }}
          </div>
        </div>
      </div>
      <div *ngSwitchCase="1" class="card-header py-1 px-2 text-truncate">
        <div class="hstack">
          <ng-icon name="bootstrap-stop-fill" class="color-advanced h-100 d-flex align-items-center"></ng-icon>
          <div class="p-0 align-middle ps-1 small">
            Advanced
            {{ getLevelString(music, difficulty) | toLevelDecimal }}
          </div>
        </div>
      </div>
      <div *ngSwitchCase="2" class="card-header py-1 px-2 text-truncate">
        <div class="hstack">
          <ng-icon name="bootstrap-stop-fill" class="color-expert h-100 d-flex align-items-center"></ng-icon>
          <div class="p-0 align-middle ps-1 small">
            Expert
            {{ getLevelString(music, difficulty) | toLevelDecimal }}
          </div>
        </div>
      </div>
      <div *ngSwitchCase="3" class="card-header py-1 px-2 text-truncate">
        <div class="hstack">
          <ng-icon name="bootstrap-stop-fill" class="color-master h-100 d-flex align-items-center"></ng-icon>
          <div class="p-0 align-middle ps-1 small">
            Master
            {{ getLevelString(music, difficulty) | toLevelDecimal }}
          </div>
        </div>
      </div>
      <div *ngSwitchCase="10" class="card-header py-1 px-2 text-truncate border border-danger bg-lunatic">
        <div class="hstack text-danger">
          <ng-icon name="bootstrap-stop-fill" class="h-100 d-flex align-items-center"></ng-icon>
          <div class="p-0 align-middle ps-1 small">
            Lunatic
            {{ getLevelString(music, difficulty) | toLevelDecimal }}
          </div>
        </div>
      </div>
    </ng-container>
    <div class="card-body py-1 px-3">
      <div class="difficulty-detail-body d-flex align-items-center justify-content-between">
        <div class="float-start small fw-bold">
          <div *ngIf="songData[difficulty]">
            <div>{{ songData[difficulty].techScoreMax }}</div>
            <div
              class="small text-secondary">{{ "Ongeki.MusicList.SongScoreRanking.PlayCount" | translate }}{{ "Common.Colon" | translate }}{{ songData[difficulty].playCount }}
            </div>
          </div>
          <div *ngIf="!songData[difficulty]">
            <div>No Record</div>
          </div>
        </div>
        <div *ngIf="songData[difficulty]" class="honor float-end">
          <img class="honor-badge"
               src="{{host}}assets/ongeki/gameUi/{{songData[difficulty].techScoreRank|toTechHonorSprite}}" alt="">
          <ng-container *ngIf="songData[difficulty].isAllBreake">
            <img class="honor-badge"
                 src="{{host}}assets/ongeki/gameUi/UI_SLC_MusicSelect_HornorBadge_AB.webp" alt="">
          </ng-container>
          <ng-container *ngIf="!songData[difficulty].isAllBreake && songData[difficulty].isFullCombo">
            <img class="honor-badge"
                 src="{{host}}assets/ongeki/gameUi/UI_SLC_MusicSelect_HornorBadge_FC.webp" alt="">
          </ng-container>
          <ng-container *ngIf="!songData[difficulty].isAllBreake && !songData[difficulty].isFullCombo">
            <img class="honor-badge"
                 src="{{host}}assets/ongeki/gameUi/UI_SLC_MusicSelect_HornorBadge_None.webp" alt="">
          </ng-container>
          <img class="honor-badge"
               src="{{host}}assets/ongeki/gameUi/UI_SLC_MusicSelect_HornorBadge_{{songData[difficulty].isFullBell?'FB':'None'}}.webp"
               alt="">
        </div>
      </div>
    </div>
  </div>
</ng-template>

<ng-template #rankingTable let-playerRanking="playerRanking">
  <div *ngIf="playerRanking" class="callout callout-info mt-2 mb-1">
    {{
      "Ongeki.MusicList.SongScoreRanking.RankingInfo" | translate: {
        ranking: (playerRanking.rank | ordinal),
        total: playerRanking.playedCount
      }
    }}
  </div>
  <table class="table table-striped table-borderless mb-0">
    <thead>
    <th>No.</th>
    <th>Username</th>
    <th>Score</th>
    </thead>
    <tbody>
    <tr *ngFor="let item of ranking; index as i">
      <td [ngSwitch]="i">
        <img *ngSwitchCase="0" class="medal" src="{{host}}assets/gold-medal.svg" alt="">
        <img *ngSwitchCase="1" class="medal" src="{{host}}assets/silver-medal.svg" alt="">
        <img *ngSwitchCase="2" class="medal" src="{{host}}assets/bronze-medal.svg" alt="">
        <span *ngIf="i !== 0 && i !== 1 && i !== 2">
                  {{ i + 1 }}
                  </span>
      </td>
      <td>{{ item.username | fullWidth }}</td>
      <td>{{ item.score }}</td>
    </tr>
    </tbody>
  </table>
</ng-template>
