// src/app/sega/ongeki/ongeki-card-level/ongeki-card-level.component.ts
import {Component, OnInit} from '@angular/core';
import {AttributeType} from '../model/OngekiEnums';
import {environment} from '../../../../environments/environment';

@Component({
    selector: 'app-ongeki-card-level',
    templateUrl: './ongeki-card-level.component.html',
    styleUrls: ['./ongeki-card-level.component.css'],
    inputs: ['level', 'attribute'],
    standalone: false
})
export class OngekiCardLevelComponent implements OnInit {

  protected readonly AttributeType = AttributeType;
  protected readonly Math = Math;
  host = environment.assetsHost;
  level: number;
  attribute: string;
  constructor() { }

  ngOnInit(): void {
  }

}

<div class="level-container ratio user-select-none"
  style="background-image: url({{host}}assets/ongeki/gameUi/UI_CMN_CharaLevel_base.webp)">
  <div class="hstack w-100 align-items-center" style="padding-left: 6%">
    <img class="h-75"
      src="{{host}}assets/ongeki/gameUi/UI_CMN_AttributeIcon_{{attribute}}_mini.webp">
      <img class="level-header"
        src="{{host}}assets/ongeki/gameUi/UI_CMN_CharaLevel_base_Header.webp">
        @if (level>=100) {
          <img
            class="level-number"
            style="margin-left: -10%"
            src="{{host}}assets/ongeki/gameUi/UI_NUM_13pt_Charalevel_00/{{Math.floor(level/100)}}.webp">
          }
          @if (level>=10) {
            <img
              class="level-number"
              style="margin-left: {{level>=100?'-12%':'-7%'}}"
              src="{{host}}assets/ongeki/gameUi/UI_NUM_13pt_Charalevel_00/{{Math.floor((level%100)/10)}}.webp">
            }
            <img style="margin-left: {{level>=10?'-10%':'-5%'}}"
            class="level-number"
            src="{{host}}assets/ongeki/gameUi/UI_NUM_13pt_Charalevel_00/{{level%10}}.webp">
          </div>
        </div>

// src/features/ongeki/OngekiCardLevel.tsx
import { assetsHost } from '@/lib/utils';
import './ongeki-common.css';

/** 等价旧版 ongeki-card-level.component（卡牌等级条） */
export function OngekiCardLevel({
  level,
  attribute,
  className,
}: {
  level: number;
  attribute: string;
  className?: string;
}) {
  return (
    <div
      className={'level-container ratio user-select-none' + (className ? ' ' + className : '')}
      style={{
        backgroundImage: `url(${assetsHost}assets/ongeki/gameUi/UI_CMN_CharaLevel_base.webp)`,
      }}
    >
      <div className="hstack w-100 align-items-center" style={{ paddingLeft: '6%' }}>
        <img
          className="h-75"
          src={assetsHost + `assets/ongeki/gameUi/UI_CMN_AttributeIcon_${attribute}_mini.webp`}
          alt=""
        />
        <img
          className="level-header"
          src={assetsHost + 'assets/ongeki/gameUi/UI_CMN_CharaLevel_base_Header.webp'}
          alt=""
        />
        {level >= 100 && (
          <img
            className="level-number"
            style={{ marginLeft: '-10%' }}
            src={assetsHost + `assets/ongeki/gameUi/UI_NUM_13pt_Charalevel_00/${Math.floor(level / 100)}.webp`}
            alt=""
          />
        )}
        {level >= 10 && (
          <img
            className="level-number"
            style={{ marginLeft: level >= 100 ? '-12%' : '-7%' }}
            src={
              assetsHost + `assets/ongeki/gameUi/UI_NUM_13pt_Charalevel_00/${Math.floor((level % 100) / 10)}.webp`
            }
            alt=""
          />
        )}
        <img
          style={{ marginLeft: level >= 10 ? '-10%' : '-5%' }}
          className="level-number"
          src={assetsHost + `assets/ongeki/gameUi/UI_NUM_13pt_Charalevel_00/${level % 10}.webp`}
          alt=""
        />
      </div>
    </div>
  );
}
